 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean','install']
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'gcr.io/logical-seat-340007/first-image', '--build-arg=JAR_FILE=target/gcpbuild-0.0.1-SNAPSHOT.jar', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/logical-seat-340007/first-image']
 images: ['gcr.io/logical-seat-340007/first-image']
